steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      gcloud compute ssh instance-1 \
        --project=clouds-labs-403019 \
        --zone=us-central1-a \
        --command="/home/viktoriia_starynchuk_ir_2021/deploy.sh"
