steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh instance-1 --zone=us-central1-a --command='/bin/sh /home/viktoriia_starynchuk_ir_2021/deploy.sh'
#
